language: node_js

node_js:
  - "10"

services:
  - docker

branches:
  only:
    - master

before_install:
  - export TZ=Asia/Shanghai

install:
  - npm install
  - npm install hexo-cli -g
  - docker pull arachnysdocker/athenapdf
  - docker pull nginx
  - wget https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh
  - chmod +x wait-for-it.sh

before_script:
  # Generate
  - hexo generate
  # Prepare nginx
  - docker run --name web -d -p 80:80 -v $(pwd)/public:/usr/share/nginx/html:ro nginx
  - NGX_IP=$(docker inspect --format '{{ .NetworkSettings.IPAddress }}' web)
  - echo $NGX_IP
  - ./wait-for-it.sh 127.0.0.1:80
  # Render
  - docker run --rm -v $(pwd)/public/resume:/converted arachnysdocker/athenapdf athenapdf --margins=none http://$NGX_IP/resume/ wi1dcard.pdf
  - docker stop web
  # Replace ssh key
  - rm -f ~/.ssh/id_rsa
  - (echo $GH_DEPLOY_KEY | base64 --decode) > ~/.ssh/id_rsa
  - chmod 400 ~/.ssh/id_rsa

script:
  # Deploy
  - hexo deploy

notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always
