dist: bionic
language: node_js
node_js: [ "12" ]
services: [ docker ]

git:
  depth: 1

env:
  global:
    - DOCKER_IMAGE=wi1dcard/blog
    - DOCKER_TAG=build-$TRAVIS_BUILD_NUMBER

branches:
  only:
    - master

install:
  - yarn install --production

before_script:
  - build/build.sh

script:
  - deploy/deploy.sh

after_script:
  - docker stop $(docker container ls -q)

notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always
