language: node_js

node_js:
  - "10"

git:
  depth: 1

services:
  - docker

branches:
  only:
    - master

install:
  - yarn install
  - export PATH=$PATH:$(pwd)/node_modules/.bin
  - docker pull arachnysdocker/athenapdf
  - docker pull nginx
  - wget https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh
  - chmod +x wait-for-it.sh

before_script:
  # Lint first
  - ./lint.sh
  # Generate
  - hexo generate
  # Render
  - docker run --net host -d -v $(pwd)/public:/usr/share/nginx/html:ro nginx
  - docker run --net host --rm -v $(pwd)/public/resume:/converted arachnysdocker/athenapdf athenapdf --margins=none http://localhost/resume/ wi1dcard.pdf
  # Replace ssh key
  - (echo $GH_DEPLOY_KEY | base64 --decode) > ~/.ssh/id_rsa
  - chmod 400 ~/.ssh/id_rsa

script:
  # Deploy
  - hexo deploy

notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always
