language: node_js

node_js:
  - "12"

git:
  depth: 1

services:
  - docker

branches:
  only:
    - master

before_script:
  # Install
  - yarn install --production
  - export PATH=$PATH:$(pwd)/node_modules/.bin
  # Lint
  - ./lint.sh
  # Build
  - yarn run build
  # Render
  - docker run --net host -d -v $(pwd)/public:/usr/share/nginx/html:ro nginx
  - docker run --net host --rm -v $(pwd)/public/resume:/converted arachnysdocker/athenapdf athenapdf --margins=none http://localhost/resume/ wi1dcard.pdf
  # Build image
  - docker build -t wi1dcard/blog .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # Replace SSH key
  - (echo $GH_DEPLOY_KEY | base64 --decode) > ~/.ssh/id_rsa
  - chmod 400 ~/.ssh/id_rsa

script:
  # Deploy
  - hexo deploy
  - docker push wi1dcard/blog

notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always
