language: node_js

node_js:
  - "10"

services:
  - docker

branches:
  only:
    - master

install:
  - npm install
  - npm install hexo-cli -g
  - docker pull arachnysdocker/athenapdf

script:
  # Generate
  - hexo generate
  # Render
  - docker run --name web -d -p 80:80 -v $(pwd)/public:/usr/share/nginx/html:ro nginx
  - IP=$(docker inspect --format '{{ .NetworkSettings.IPAddress }}' web)
  - docker run --rm -v $(pwd)/public/resume:/converted arachnysdocker/athenapdf athenapdf --margins=none http://$IP/resume/ wi1dcard.pdf
  - docker stop web
  # Replace ssh key
  - rm -f ~/.ssh/id_rsa
  - (echo $GH_DEPLOY_KEY | base64 --decode) > ~/.ssh/id_rsa
  - chmod 400 ~/.ssh/id_rsa
  # Deploy
  - hexo deploy

notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always
