language: node_js

node_js:
  - "10"

branches:
  only:
  - master

install:
  - npm install
  - npm install hexo-cli -g

before_script:
  - rm -f ~/.ssh/id_rsa
  - (echo $GH_DEPLOY_KEY | base64 --decode) > ~/.ssh/id_rsa
  - chmod 400 ~/.ssh/id_rsa

script:
  - hexo deploy -g